package model;
// Generated Mar 5, 2017 11:25:18 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

    private Integer idCategory;
    private String category;
    private Set<Post> posts = new HashSet<Post>(0);

    public Categories() {
    }

    public Categories(String category) {
        this.category = category;
    }

    public Categories(String category, Set<Post> posts) {
        this.category = category;
        this.posts = posts;
    }

    public Integer getIdCategory() {
        return this.idCategory;
    }

    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Set<Post> getPosts() {
        return this.posts;
    }

    public void setPosts(Set<Post> posts) {
        this.posts = posts;
    }

}
