package model;
// Generated Mar 7, 2017 2:13:47 PM by Hibernate Tools 4.3.1



/**
 * Dislikes generated by hbm2java
 */
public class Dislikes  implements java.io.Serializable {


     private Integer idDislike;
     private Post post;
     private User user;

    public Dislikes() {
    }

    public Dislikes(Post post, User user) {
       this.post = post;
       this.user = user;
    }
   
    public Integer getIdDislike() {
        return this.idDislike;
    }
    
    public void setIdDislike(Integer idDislike) {
        this.idDislike = idDislike;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


