package model;
// Generated Mar 7, 2017 2:13:47 PM by Hibernate Tools 4.3.1



/**
 * Likes generated by hbm2java
 */
public class Likes  implements java.io.Serializable {


     private Integer idLike;
     private Post post;
     private User user;

    public Likes() {
    }

    public Likes(Post post, User user) {
       this.post = post;
       this.user = user;
    }
   
    public Integer getIdLike() {
        return this.idLike;
    }
    
    public void setIdLike(Integer idLike) {
        this.idLike = idLike;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


