package model;
// Generated Mar 6, 2017 5:35:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer idMessage;
     private User userByIdReceiver;
     private User userByIdSender;
     private String isi;
     private Date dateTime;

    public Message() {
    }

    public Message(User userByIdReceiver, User userByIdSender, String isi, Date dateTime) {
       this.userByIdReceiver = userByIdReceiver;
       this.userByIdSender = userByIdSender;
       this.isi = isi;
       this.dateTime = dateTime;
    }
   
    public Integer getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }
    public User getUserByIdReceiver() {
        return this.userByIdReceiver;
    }
    
    public void setUserByIdReceiver(User userByIdReceiver) {
        this.userByIdReceiver = userByIdReceiver;
    }
    public User getUserByIdSender() {
        return this.userByIdSender;
    }
    
    public void setUserByIdSender(User userByIdSender) {
        this.userByIdSender = userByIdSender;
    }
    public String getIsi() {
        return this.isi;
    }
    
    public void setIsi(String isi) {
        this.isi = isi;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


