package model;
// Generated Mar 5, 2017 11:25:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer idPost;
     private Categories categories;
     private User user;
     private String judul;
     private String isi;
     private Date dateTime;
     private int likePost;
     private int dislikePost;
     private Set<Report> reports = new HashSet<Report>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<User> users = new HashSet<User>(0);
     private Set<User> users_1 = new HashSet<User>(0);

    public Post() {
    }

	
    public Post(Categories categories, User user, String judul, String isi, Date dateTime, int likePost, int dislikePost) {
        this.categories = categories;
        this.user = user;
        this.judul = judul;
        this.isi = isi;
        this.dateTime = dateTime;
        this.likePost = likePost;
        this.dislikePost = dislikePost;
    }
    public Post(Categories categories, User user, String judul, String isi, Date dateTime, int likePost, int dislikePost, Set<Report> reports, Set<Comment> comments, Set<User> users, Set<User> users_1) {
       this.categories = categories;
       this.user = user;
       this.judul = judul;
       this.isi = isi;
       this.dateTime = dateTime;
       this.likePost = likePost;
       this.dislikePost = dislikePost;
       this.reports = reports;
       this.comments = comments;
       this.users = users;
       this.users_1 = users_1;
    }
   
    public Integer getIdPost() {
        return this.idPost;
    }
    
    public void setIdPost(Integer idPost) {
        this.idPost = idPost;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getIsi() {
        return this.isi;
    }
    
    public void setIsi(String isi) {
        this.isi = isi;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public int getLikePost() {
        return this.likePost;
    }
    
    public void setLikePost(int likePost) {
        this.likePost = likePost;
    }
    public int getDislikePost() {
        return this.dislikePost;
    }
    
    public void setDislikePost(int dislikePost) {
        this.dislikePost = dislikePost;
    }
    public Set<Report> getReports() {
        return this.reports;
    }
    
    public void setReports(Set<Report> reports) {
        this.reports = reports;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<User> getUsers_1() {
        return this.users_1;
    }
    
    public void setUsers_1(Set<User> users_1) {
        this.users_1 = users_1;
    }




}


