package model;
// Generated Feb 25, 2017 12:52:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer idPost;
     private User user;
     private String judul;
     private String isi;
     private Date dateTime;
     private int likePost;
     private int dislikePost;
     private Set<Report> reports = new HashSet<Report>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);

    public Post() {
    }

	
    public Post(User user, String judul, String isi, Date dateTime, int likePost, int dislikePost) {
        this.user = user;
        this.judul = judul;
        this.isi = isi;
        this.dateTime = dateTime;
        this.likePost = likePost;
        this.dislikePost = dislikePost;
    }
    public Post(User user, String judul, String isi, Date dateTime, int likePost, int dislikePost, Set<Report> reports, Set<Comment> comments) {
       this.user = user;
       this.judul = judul;
       this.isi = isi;
       this.dateTime = dateTime;
       this.likePost = likePost;
       this.dislikePost = dislikePost;
       this.reports = reports;
       this.comments = comments;
    }
   
    public Integer getIdPost() {
        return this.idPost;
    }
    
    public void setIdPost(Integer idPost) {
        this.idPost = idPost;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getIsi() {
        return this.isi;
    }
    
    public void setIsi(String isi) {
        this.isi = isi;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public int getLikePost() {
        return this.likePost;
    }
    
    public void setLikePost(int likePost) {
        this.likePost = likePost;
    }
    public int getDislikePost() {
        return this.dislikePost;
    }
    
    public void setDislikePost(int dislikePost) {
        this.dislikePost = dislikePost;
    }
    public Set<Report> getReports() {
        return this.reports;
    }
    
    public void setReports(Set<Report> reports) {
        this.reports = reports;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }

    @Override
    public String toString() {
        return "Post{" + "idPost=" + idPost + ", judul=" + judul + ", isi=" + isi + ", dateTime=" + dateTime + ", likePost=" + likePost + ", dislikePost=" + dislikePost + '}';
    }

}


