package model;
// Generated Feb 24, 2017 4:52:52 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer idPost;
     private User user;
     private String judul;
     private String isi;
     private Date dateTime;
     private Set reports = new HashSet(0);
     private Set comments = new HashSet(0);

    public Post() {
    }

	
    public Post(User user, String judul, String isi, Date dateTime) {
        this.user = user;
        this.judul = judul;
        this.isi = isi;
        this.dateTime = dateTime;
    }
    public Post(User user, String judul, String isi, Date dateTime, Set reports, Set comments) {
       this.user = user;
       this.judul = judul;
       this.isi = isi;
       this.dateTime = dateTime;
       this.reports = reports;
       this.comments = comments;
    }
   
    public Integer getIdPost() {
        return this.idPost;
    }
    
    public void setIdPost(Integer idPost) {
        this.idPost = idPost;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getIsi() {
        return this.isi;
    }
    
    public void setIsi(String isi) {
        this.isi = isi;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Set getReports() {
        return this.reports;
    }
    
    public void setReports(Set reports) {
        this.reports = reports;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


