package model;
// Generated Feb 21, 2017 9:01:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Thread generated by hbm2java
 */
public class Thread  implements java.io.Serializable {


     private Integer idThread;
     private User user;
     private String judul;
     private String isi;
     private Date dateTime;
     private Set<Report> reports = new HashSet<Report>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);

    public Thread() {
    }

	
    public Thread(User user, String judul, String isi, Date dateTime) {
        this.user = user;
        this.judul = judul;
        this.isi = isi;
        this.dateTime = dateTime;
    }
    public Thread(User user, String judul, String isi, Date dateTime, Set<Report> reports, Set<Comment> comments) {
       this.user = user;
       this.judul = judul;
       this.isi = isi;
       this.dateTime = dateTime;
       this.reports = reports;
       this.comments = comments;
    }
   
    public Integer getIdThread() {
        return this.idThread;
    }
    
    public void setIdThread(Integer idThread) {
        this.idThread = idThread;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getIsi() {
        return this.isi;
    }
    
    public void setIsi(String isi) {
        this.isi = isi;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Set<Report> getReports() {
        return this.reports;
    }
    
    public void setReports(Set<Report> reports) {
        this.reports = reports;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }




}


