package model;
// Generated Feb 24, 2017 4:52:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String firstName;
     private String lastName;
     private String email;
     private String jenisKelamin;
     private String urlFoto;
     private String username;
     private String password;
     private Set messagesForIdReceiver = new HashSet(0);
     private Set replies = new HashSet(0);
     private Set comments = new HashSet(0);
     private Set messagesForIdSender = new HashSet(0);
     private Set posts = new HashSet(0);
     private Set reports = new HashSet(0);

    public User() {
    }

	
    public User(String firstName, String lastName, String email, String jenisKelamin, String urlFoto, String username, String password) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.jenisKelamin = jenisKelamin;
        this.urlFoto = urlFoto;
        this.username = username;
        this.password = password;
    }
    public User(String firstName, String lastName, String email, String jenisKelamin, String urlFoto, String username, String password, Set messagesForIdReceiver, Set replies, Set comments, Set messagesForIdSender, Set posts, Set reports) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.jenisKelamin = jenisKelamin;
       this.urlFoto = urlFoto;
       this.username = username;
       this.password = password;
       this.messagesForIdReceiver = messagesForIdReceiver;
       this.replies = replies;
       this.comments = comments;
       this.messagesForIdSender = messagesForIdSender;
       this.posts = posts;
       this.reports = reports;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }
    public String getUrlFoto() {
        return this.urlFoto;
    }
    
    public void setUrlFoto(String urlFoto) {
        this.urlFoto = urlFoto;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getMessagesForIdReceiver() {
        return this.messagesForIdReceiver;
    }
    
    public void setMessagesForIdReceiver(Set messagesForIdReceiver) {
        this.messagesForIdReceiver = messagesForIdReceiver;
    }
    public Set getReplies() {
        return this.replies;
    }
    
    public void setReplies(Set replies) {
        this.replies = replies;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getMessagesForIdSender() {
        return this.messagesForIdSender;
    }
    
    public void setMessagesForIdSender(Set messagesForIdSender) {
        this.messagesForIdSender = messagesForIdSender;
    }
    public Set getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set posts) {
        this.posts = posts;
    }
    public Set getReports() {
        return this.reports;
    }
    
    public void setReports(Set reports) {
        this.reports = reports;
    }




}


