package model;
// Generated Mar 7, 2017 2:13:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String firstName;
     private String lastName;
     private String email;
     private String jenisKelamin;
     private String urlFoto;
     private String username;
     private String password;
     private int level;
     private Date dateTime;
     private int progressLevel;
     private Set<Dislikes> dislikeses = new HashSet<Dislikes>(0);
     private Set<Message> messagesForIdReceiver = new HashSet<Message>(0);
     private Set<Reply> replies = new HashSet<Reply>(0);
     private Set<Likes> likeses = new HashSet<Likes>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<Message> messagesForIdSender = new HashSet<Message>(0);
     private Set<Post> posts = new HashSet<Post>(0);
     private Set<Report> reports = new HashSet<Report>(0);

    public User() {
    }

	
    public User(String firstName, String lastName, String email, String jenisKelamin, String urlFoto, String username, String password, int level, Date dateTime, int progressLevel) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.jenisKelamin = jenisKelamin;
        this.urlFoto = urlFoto;
        this.username = username;
        this.password = password;
        this.level = level;
        this.dateTime = dateTime;
        this.progressLevel = progressLevel;
    }
    public User(String firstName, String lastName, String email, String jenisKelamin, String urlFoto, String username, String password, int level, Date dateTime, int progressLevel, Set<Dislikes> dislikeses, Set<Message> messagesForIdReceiver, Set<Reply> replies, Set<Likes> likeses, Set<Comment> comments, Set<Message> messagesForIdSender, Set<Post> posts, Set<Report> reports) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.jenisKelamin = jenisKelamin;
       this.urlFoto = urlFoto;
       this.username = username;
       this.password = password;
       this.level = level;
       this.dateTime = dateTime;
       this.progressLevel = progressLevel;
       this.dislikeses = dislikeses;
       this.messagesForIdReceiver = messagesForIdReceiver;
       this.replies = replies;
       this.likeses = likeses;
       this.comments = comments;
       this.messagesForIdSender = messagesForIdSender;
       this.posts = posts;
       this.reports = reports;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }
    public String getUrlFoto() {
        return this.urlFoto;
    }
    
    public void setUrlFoto(String urlFoto) {
        this.urlFoto = urlFoto;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public int getProgressLevel() {
        return this.progressLevel;
    }
    
    public void setProgressLevel(int progressLevel) {
        this.progressLevel = progressLevel;
    }
    public Set<Dislikes> getDislikeses() {
        return this.dislikeses;
    }
    
    public void setDislikeses(Set<Dislikes> dislikeses) {
        this.dislikeses = dislikeses;
    }
    public Set<Message> getMessagesForIdReceiver() {
        return this.messagesForIdReceiver;
    }
    
    public void setMessagesForIdReceiver(Set<Message> messagesForIdReceiver) {
        this.messagesForIdReceiver = messagesForIdReceiver;
    }
    public Set<Reply> getReplies() {
        return this.replies;
    }
    
    public void setReplies(Set<Reply> replies) {
        this.replies = replies;
    }
    public Set<Likes> getLikeses() {
        return this.likeses;
    }
    
    public void setLikeses(Set<Likes> likeses) {
        this.likeses = likeses;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public Set<Message> getMessagesForIdSender() {
        return this.messagesForIdSender;
    }
    
    public void setMessagesForIdSender(Set<Message> messagesForIdSender) {
        this.messagesForIdSender = messagesForIdSender;
    }
    public Set<Post> getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set<Post> posts) {
        this.posts = posts;
    }
    public Set<Report> getReports() {
        return this.reports;
    }
    
    public void setReports(Set<Report> reports) {
        this.reports = reports;
    }

    public String getFullName(){
        return this.firstName+this.lastName;
    }
}


